apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-config
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/nstogner/gops-flux-config
  ref:
    branch: main
