apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: example-cluster-1-fluxcd
  namespace: same-ns-as-secret
spec:
  interval: 2m
  retryInterval: 1m
  kubeConfig:
    secretRef:
      # This secret should contain a field (.data.value) which contains the kubeconfig.
      name: example-cluster-1-kubeconfig
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
    namespace: flux-system
  path: "./fluxcd"
